export const UPDATE_USERINFO = "UPDATE_USERINFO";
//网络请求
export const UPDATE_USERINFO_STARTED = "UPDATE_USERINFO_STARTED";
export const UPDATE_USERINFO_SUCCESS = "UPDATE_USERINFO_SUCCESS";
export const UPDATE_USERINFO_FAILURE = "UPDATE_USERINFO_FAILURE";
