export const CHANGE_PAGE = "CHANGE_PAGE";
export const GET_USERINFO = "GET_USERINFO";
//网络请求
export const FETCH_USERINFO_STARTED = "FETCH_USERINFO_STARTED";
export const FETCH_USERINFO_SUCCESS = "FETCH_USERINFO_SUCCESS";
export const FETCH_USERINFO_FAILURE = "FETCH_USERINFO_FAILURE";
